In [1]:
import pickle
import pandas as pd

In [2]:
with open('Pickles/game_logs_2018_position.pickle', 'rb') as handle:
    game_logs_2018_position = pickle.load(handle)

In [3]:
game_logs_2018_position

                         Date               Home Tm               Away Tm  PA  \
Name
Barnes, Austin 0   2018-03-29   Los Angeles Dodgers  San Francisco Giants   0
               2   2018-03-31   Los Angeles Dodgers  San Francisco Giants   3
               3   2018-04-01   Los Angeles Dodgers  San Francisco Giants   1
               4   2018-04-02  Arizona Diamondbacks   Los Angeles Dodgers   1
               5   2018-04-03  Arizona Diamondbacks   Los Angeles Dodgers   3
...                       ...                   ...                   ...  ..
Turner, Justin 58  2018-08-09      Colorado Rockies   Los Angeles Dodgers   5
               59  2018-08-10      Colorado Rockies   Los Angeles Dodgers   5
               60  2018-08-11      Colorado Rockies   Los Angeles Dodgers   4
               61  2018-08-12      Colorado Rockies   Los Angeles Dodgers   2
               62  2018-08-13   Los Angeles Dodgers  San Francisco Giants   4

                   AB  R  H  2B  3B  HR  RBI  BB  SO  SB  CS  HBP    AVG  \
Name
Barnes, Austin 0    0  0  0   0   0   0    0   0   0   0   0    0   .---
               2    2  1  0   0   0   0    0   1   1   0   0    0   .000
               3    1  0  1   0   0   0    1   0   0   0   0    0   .333
               4    1  0  1   0   0   0    0   0   0   0   0    0   .500
               5    3  1  1   1   0   0    0   0   0   0   0    0   .429
...                .. .. ..  ..  ..  ..  ...  ..  ..  ..  ..  ...    ...
Turner, Justin 58   5  0  2   0   0   0    0   0   1   0   0    0  0.266
               59   3  2  2   1   0   0    0   0   0   0   0    2  0.272
               60   4  0  2   0   1   0    1   0   0   0   0    0  0.277
               61   2  1  1   1   0   0    0   0   0   0   0    0  0.279
               62   4  1  2   0   0   1    1   0   0   0   0    0  0.284

                     OBP    SLG    OPS
Name
Barnes, Austin 0    .---   .---  0.000
               2    .333   .000  0.333
               3    .500   .333  0.833
               4    .600   .500  1.100
               5    .500   .571  1.071
...                  ...    ...    ...
Turner, Justin 58  0.362   0.41  0.772
               59  0.372  0.419  0.791
               60  0.374  0.431  0.805
               61  0.376  0.437  0.812
               62  0.378  0.453  0.830

[566 rows x 20 columns]